// Build orchestrator.
//
//   node build.js            -> generate tokens, then concat everything into dist/
//   node build.js tokens     -> only regenerate the SD token CSS
//   node build.js --check    -> lint component CSS for hardcoded aesthetic values
//
// The plan traded "no build step" for a JSON single source of truth (see README).
// This script is the whole build: Style Dictionary for tokens, plus a dependency-free
// concatenation for the shipped bundles.

import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync, copyFileSync } from 'node:fs';
import { join } from 'node:path';
import { buildTokens, THEMES } from './sd.config.js';

const ROOT = new URL('.', import.meta.url).pathname;
const p = (...s) => join(ROOT, ...s);

const BANNER = `/*!
 * bleed.css — aesthetic-agnostic component library (default theme: bleed)
 * Generated by build.js. Do not edit dist/ directly; edit src/ + tokens/ and rebuild.
 * @layer bleed.tokens, bleed.base, bleed.components — consumer unlayered CSS wins.
 */\n`;

// Cascade layer order is declared ONCE, first, so the ordering holds regardless of
// the order blocks physically appear later in the bundle.
const LAYER_DECL = '@layer bleed.tokens, bleed.base, bleed.components;\n';

// Component groups, in bundle order. `core: false` => excluded from bleed-core.css.
// (groups 3-5 must not depend on finance, which is what makes the core build valid.)
const GROUPS = [
  { name: 'primitives', dir: 'src/primitives', core: true },
  { name: 'finance', dir: 'src/finance', core: false },
  { name: 'layout', dir: 'src/layout', core: true },
  { name: 'inputs', dir: 'src/inputs', core: true },
  { name: 'feedback', dir: 'src/feedback', core: true },
];

function cssFiles(dir) {
  const abs = p(dir);
  if (!existsSync(abs)) return [];
  return readdirSync(abs)
    .filter((f) => f.endsWith('.css'))
    .sort()
    .map((f) => join(dir, f));
}

function read(rel) {
  return readFileSync(p(rel), 'utf8').trimEnd() + '\n';
}

function section(title) {
  return `\n/* ${'='.repeat(4)} ${title} ${'='.repeat(Math.max(4, 68 - title.length))} */\n`;
}

// --- foundation layer files, in dependency order ------------------------------
function foundationFiles() {
  const files = ['src/foundations/tokens.css'];
  for (const t of THEMES) files.push(`src/foundations/themes/${t}.css`);
  files.push('src/foundations/runtime.css'); // @property + density-derived + color-scheme
  files.push('src/foundations/base.css'); // @layer bleed.base
  return files;
}

function assemble({ includeFinance }) {
  let out = BANNER + LAYER_DECL;

  out += section('FOUNDATIONS');
  for (const f of foundationFiles()) out += read(f);

  for (const group of GROUPS) {
    if (!includeFinance && !group.core) continue;
    const files = cssFiles(group.dir);
    if (!files.length) continue;
    out += section(group.name.toUpperCase());
    for (const f of files) out += read(f);
  }
  return out;
}

// --- lint: component CSS must carry zero aesthetic values ----------------------
// Everything visual flows through a token. A hex/rgb/hsl/oklch literal or a bare
// px length in component CSS is a bug: it can't be re-themed.
// A literal color = hex, or a color FUNCTION applied to raw channels: rgb()/hsl()/
// oklch()/… with a `(`. Note `color-mix(in oklch, …)` is allowed — the `in oklch`
// color-space keyword has no paren, and mixing var()s is the themeable pattern; any
// literal color *inside* a color-mix (a hex or oklch() arg) is still caught here.
const COLOR_LITERAL = /#[0-9a-fA-F]{3,8}\b|\b(?:rgba?|hsla?|oklch|oklab|lab|lch)\s*\(/;
// px is allowed only for hairline/optical details we explicitly whitelist inline
// via a trailing `/* px-ok */` comment on the same line.
const PX_LITERAL = /\b\d*\.?\d+px\b/;

function lint() {
  const problems = [];
  for (const group of GROUPS) {
    for (const rel of cssFiles(group.dir)) {
      const lines = read(rel).split('\n');
      lines.forEach((line, i) => {
        const code = line.replace(/\/\*.*?\*\//g, '').trimEnd();
        if (!code || code.trimStart().startsWith('/*')) return;
        if (COLOR_LITERAL.test(code)) {
          problems.push(`${rel}:${i + 1}  color literal → ${code.trim()}`);
        }
        if (PX_LITERAL.test(code) && !/px-ok/.test(line)) {
          problems.push(`${rel}:${i + 1}  raw px (use a token, or mark /* px-ok */) → ${code.trim()}`);
        }
      });
    }
  }
  if (problems.length) {
    console.error(`\n✗ ${problems.length} hardcoded aesthetic value(s) in component CSS:\n`);
    console.error(problems.map((x) => '  ' + x).join('\n'));
    console.error('\nComponents must make NO aesthetic assumptions — route through a token.\n');
    process.exit(1);
  }
  console.log('✓ lint: component CSS carries zero hardcoded aesthetic values');
}

// --- main ----------------------------------------------------------------------
const arg = process.argv[2];

if (arg === '--check') {
  lint();
} else {
  console.log('› building tokens (Style Dictionary)…');
  await buildTokens();
  console.log(`  wrote src/foundations/tokens.css + ${THEMES.length} theme files`);

  if (arg === 'tokens') process.exit(0);

  if (!existsSync(p('dist'))) mkdirSync(p('dist'));

  const full = assemble({ includeFinance: true });
  writeFileSync(p('dist/bleed.css'), full);
  console.log(`› wrote dist/bleed.css (${(full.length / 1024).toFixed(1)} kB)`);

  const core = assemble({ includeFinance: false });
  writeFileSync(p('dist/bleed-core.css'), core);
  console.log(`› wrote dist/bleed-core.css (${(core.length / 1024).toFixed(1)} kB, no finance/)`);

  if (existsSync(p('src/bleed.js'))) {
    copyFileSync(p('src/bleed.js'), p('dist/bleed.js'));
    console.log('› copied dist/bleed.js');
  }
  console.log('done.');
}
