/**
 * # Build orchestrator
 * Style Dictionary for tokens, plus dependency-free concatenation for shipped bundles.
 *
 * Usage:
 *  - node scripts/build.js   -> generate tokens, then concat everything into dist/
 */

import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync, copyFileSync } from "node:fs";
import { join } from "node:path";
import { buildTokens, THEMES } from "../sd.config.js";

const ROOT = new URL("../", import.meta.url).pathname;

// component groups
const GROUPS = [
  { name: "PRIMITIVES", dir: "src/primitives" },
  { name: "LAYOUT", dir: "src/layout" },
  { name: "INPUTS", dir: "src/inputs" },
  { name: "FEEDBACK", dir: "src/feedback" },
  { name: "FINANCE", dir: "src/finance" },
];

// generate section title
function section(title) {
  return `\n/* ${"=".repeat(4)} ${title} ${"=".repeat(Math.max(4, 68 - title.length))} */\n`;
}

// lists the .css files inside a given source directory, returning them as bundle-ready relative paths
function cssFiles(dir) {
  const abs = join(ROOT, dir);
  if (!existsSync(abs)) return [];
  return readdirSync(abs)
    .filter((f) => f.endsWith(".css"))
    .sort()
    .map((f) => join(dir, f));
}

// returns file contents
function read(rel) {
  return readFileSync(join(ROOT, rel), "utf8").trimEnd() + "\n";
}

// builds one full CSS bundle string as text, in a fixed order
function assemble() {
  let out = `/*!
 * Generated by scripts/build.js. Do not edit dist/ directly; edit src/ + tokens/ and rebuild.
 */

/* Cascade layer order declared first to maintain ordering regardless of where layers appear later in the bundle. */
@layer bleed.tokens, bleed.base, bleed.components;
`;

  // retrieve foundation files
  const foundationFiles = ["src/foundations/tokens.css"];
  for (const theme of THEMES) {
    foundationFiles.push(`src/foundations/themes/${theme}.css`);
  }
  foundationFiles.push("src/foundations/runtime.css"); // @property + density-derived + color-scheme
  foundationFiles.push("src/foundations/base.css"); // @layer bleed.base

  // assemble foundation files
  out += section("FOUNDATIONS");
  for (const file of foundationFiles) {
    out += read(file);
  }

  // assemble the rest
  for (const group of GROUPS) {
    const files = cssFiles(group.dir);
    if (!files.length) continue;
    out += section(group.name);
    for (const file of files) {
      out += read(file);
    }
  }

  return out;
}

// --- main ----------------------------------------------------------------------
const arg = process.argv[2];

// build tokens
console.log("› building tokens...");
await buildTokens();
console.log(`› wrote src/foundations/tokens.css + ${THEMES.length} theme files`);

// build css file into dist
if (!existsSync(join(ROOT, "dist"))) mkdirSync(join(ROOT, "dist"));
const full = assemble();
writeFileSync(join(ROOT, "dist/bleed.css"), full);
console.log(`› wrote dist/bleed.css (${(full.length / 1024).toFixed(1)} kB)`);

// copy js file into dist
if (existsSync(join(ROOT, "src/bleed.js"))) {
  copyFileSync(join(ROOT, "src/bleed.js"), join(ROOT, "dist/bleed.js"));
  console.log("› copied dist/bleed.js");
}

console.log("done.");
